### ISSUE TITLE
addVisualQueryService

### ISSUE THREAD

**Issue by sdorresteijn88** [i2group/analyze-connect-node-sdk#10]
Good afternoon,

I really like the option to add VQ to the connectors! 

I am playing around with it and I have 4 questions, hopefully you can help me with this.

1. How can I enable the 'observed link' (LOB1)? I tried it in a few ways but I didn't get it working.

![image](https://github.com/i2group/analyze-connect-node-sdk/assets/52672945/a607bd88-6d51-4526-96ae-6776ff158fa9)

```
addVisualQueryService(
  // https://i2group.github.io/analyze-connect-node-sdk/guide/visual-query.html
  {
    id: 'visual-query-example',
    name: 'Visual query test',
    description: 'Visual query test...',
    config: {
      // allow camera ET7 and vehicle ET3 and observed link LOB1
      paletteItemTypes: { mode: 'ALLOW', itemTypeIds: ['ET3', 'ET7']},
      operatorUsageRules: [],
      constraints: {
        // Can users specify which record types they want in results?
        outputSelectionSupported: true,
        // How many items in the query structure can have count conditions?
        maximumCountConditions: 1,
        // How many query links can appear in the query structure?
        maximumQueryLinkCount: 10,
        // How many query entities can have the 'Any' type?
        maximumAnyEntityTypeSupported: 0,
        // How many query links can have the 'Any' type?
        maximumAnyLinkTypeSupported: 2,
      },
    },
  },
  // eslint-disable-next-line @typescript-eslint/require-await
  async ({ visualQuery, result }) => {
    console.log('VQ', visualQuery);
    console.log('result', result);
  }
);
```

2. The example contains still 2 typescript errors. I am also not a typescript expert so it would be nice if the examples are correct;)
![image](https://github.com/i2group/analyze-connect-node-sdk/assets/52672945/ef700ead-91cc-4cdc-b0a9-f25f62d0e070)

3. Is it possible to define default values in the VQ? In my case that I search for vehicle color = red AND observed by a camera in a specified geospatial area?

4. How can I apply the Visual Query to the result? Should I go through all the conditions or is there a build in function to filter the result based on the VQ?
```
  // eslint-disable-next-line @typescript-eslint/require-await
  async ({ visualQuery, result }) => {
    const anpr_data = getAnprData();
    console.log('VQ', visualQuery);
    console.log('result', result);
    //console.log('anpr', anpr_data);

    if (anpr_data !== undefined){
      anpr_data.forEach((cam) => {
        if (cam !== undefined){
          addSurveillanceCamera(cam, result);
        }
      });
    }
  }
```
![image](https://github.com/i2group/analyze-connect-node-sdk/assets/52672945/b9d409bf-c39b-4987-be85-2482ea626202)

This gives the logging below.
![image](https://github.com/i2group/analyze-connect-node-sdk/assets/52672945/ac5ff205-57c3-4d47-a94e-8ed8367c1be1)

**Comment by Anthony-Johnson-i2** [comment]
Hi  @sdorresteijn88 

I will see if I can get someone from development to help you here.

Cheers

**Comment by Jonny-Cornwell-i2** [comment]
Sorry for the delay! I have set up a new connector using the snippets you have provided and have used the law enforcement schema as the connector schema. This will be the basis for my replies for reference.

1. I have copied the code you have provided and it looks like you have not included the `'LOB1'` id in the list of `itemTypeIds`. When adding this it enabled me to draw a link accordingly.

<img width="1804" alt="image" src="https://github.com/i2group/analyze-connect-node-sdk/assets/97174850/4577bff5-a1e8-4f15-95bc-5728f6f049b5">

```ts

addVisualQueryService(
  {
    id: 'visual-query-example',
    name: 'Visual query test',
    description: 'Visual query test...',
    config: {
      // allow camera ET7 and vehicle ET3 and observed link LOB1
      paletteItemTypes: { mode: 'ALLOW', itemTypeIds: ['ET3', 'ET7', 'LOB1'] },
      operatorUsageRules: [],
      constraints: {
        // Can users specify which record types they want in results?
        outputSelectionSupported: true,
        // How many items in the query structure can have count conditions?
        maximumCountConditions: 1,
        // How many query links can appear in the query structure?
        maximumQueryLinkCount: 10,
        // How many query entities can have the 'Any' type?
        maximumAnyEntityTypeSupported: 0,
        // How many query links can have the 'Any' type?
        maximumAnyLinkTypeSupported: 2,
      },
    },
  },
  ({ result, visualQuery }) => {
    console.log('VQ', visualQuery);
    console.log('result', result);
  }
);
```

2. I was not able to reproduce the unsafe call issue or the in point 2, nor the require await eslint issue.
   It could potentially be related to cached types of an older DK version if the IDE hasn't been reloaded following updating the package for example. I would note the latter will not be an issue once because once fully implemented as there will be async operations within the function ([details here](https://eslint.org/docs/latest/rules/require-await)).

3. We do not currently have support for a default VQ structure as described but I can log the request internally.

4. We provide the structure that has been drawn in a raw form but turning that into a request against a source system is the implementors responsibility.
   This is done by forming a query to run against the source system, e.g. looping through the elements in the visualQuery and generating a SQL query matching the structure and conditions.
   Once the data is returned the results can be constructed.

   You typically would not bring the entire source data into the connector and post process it which it looks like the snippet is doing.

**Comment by sdorresteijn88** [comment]
Good morning @Jonny-Cornwell-i2,

Thanks for your extensive answer. 

1. I tried it but maybe I forgot to reload the plugin. Any way it works now:)
2. Thanks for your explanation.
3. This would be nice and helpful in my opinion. Or maybe the option to use saved VQs in a connector.
4. Clear, I wanted to be sure before I spent a lot of time on it and afterwards it would turn out that it could be done easier:)
