### ISSUE TITLE
Seeded search question

### ISSUE THREAD

**Issue by stvdo** [i2group/analyze-connect-node-sdk#27]
Good afternoon,

Is it somehow possible to add a constraint that a certain field of the seeded entity must be filled?

I have now the code below
```seedConstraints: { typeConstraints: [Persoon], min: 1, max: 1},```

But I would only allow person entities where the name != undefined or empty.

Now I handle this later on in the code but it would be nice that the service doesn't even popup for the end user.

**Comment by Colvin-Cowie-i2** [comment]
Hello. Not directly in this sense of saying that you want a `Person` item type with a `name` property defined.
But are you aware of the [semantic property seeded search constraints](https://i2group.github.io/analyze-connect-node-sdk/guide/property-semantic-search.html)? These allow you to specify that you accept seeds with properties of specific _semantic_ types, rather than specific item+property type ids. Semantic types can be specified through Schema Designer, see https://docs.i2group.com/analyze/4.4.4/semantic_types.html.

So you can, for example, create a service that accepts seeds containing a first name and a last name without caring about the actual item type of the seed.

In the [Example Connector](https://github.com/i2group/analyze-connect-node-sdk/tree/main/samples/example-connector) the
`Semantic Property Search` service demonstrates how to require seed records that have values for properties with specific semantic types. See the example: https://github.com/i2group/analyze-connect-node-sdk/blob/2797e776846ddb35932fb1d33148de6b0439a714/samples/example-connector/src/index.ts#L485-L524

**Comment by stvdo** [comment]
Hi @Colvin-Cowie-i2 

Cool, I wasn't aware of that functionality. It works almost as expected now. I only get Typescript errors when I try to add that person to the result with result.addEntityFromSeed(). However it works as expected. Do you have suggestions to solve the e

```const bsnNumber = semanticSeed.getAsStrings(properties.BsnNumber);
        const seedEntity = semanticSeed.seed.isType(Persoon) ? result.addEntityFromSeed(semanticSeed.seed) : undefined;```

![image](https://github.com/user-attachments/assets/3de5e33d-29d4-4af5-bcfc-21c566de0b59)

**Comment by stvdo** [comment]
It does see the printscreens below.

isType(Person)
![image](https://github.com/user-attachments/assets/cda220ba-6f69-4f8c-8009-5c3b12c8a761)

result.addEntityFromSeed(sementicSeed.seed)
![image](https://github.com/user-attachments/assets/47b9959c-f4e4-4f11-a837-3b035e1798ce)

**Comment by Jonny-Cornwell-i2** [comment]
Hi @stvdo,

When using semantic seeds the incoming record could be either a link or an entity, whilst this will work if the seed is the correct entity if a link was to be provided the connector would error for example. Based on this you'll need to check if the seed is a link or entity before checking the type add seed/entity results along with access properties of the seed, see below:

```ts
      if (!semanticSeed.seed.isLink && semanticSeed.seed.isType(Person)) {
        console.log('Age is: ', semanticSeed.seed.getProperty('Age'));
        result.addEntityFromSeed(semanticSeed.seed);
      }
```

We could potentially look at changing `isType` in the future to make it a little bit smarter but for now the typings are indicating potential problems in the code. Hope this helps!

**Comment by stvdo** [comment]
Thanks @Jonny-Cornwell-i2 this solved the issue indeed.
