### ISSUE TITLE
Getting the initial ID from the connectorKeys

### ISSUE THREAD

**Issue by Timon-IW** [i2group/analyze-connect-node-sdk#29]
Greetings,

I am trying to get the initial ID I gave the entity when creating it. The one I gave as the second attribute of the addEntity method.
I obtained it from the seed.connectorKeys object on another connector, but now it is always empty. Am I missing something? When I created the entity in the other one, I did nothing different from now. 
If you need more Input, please let me know!

Best regards,
Timon

**Comment by Mark-Falconbridge-i2** [comment]
Hi Timon,

You should just be able to access the `.id` property on the entity you added. Is that not working? If not, can you post an example to indicate what you're doing?

**Comment by Timon-IW** [comment]
Hello,

I don't know how I would do that. I only have the seed object. And on this, there is no .id property. 

So I create the entity, put it in the chart, then take it as input for a seeded search. There, I want to get the ID I originally added on there. But I don't want it to be a property of the entity. 

I hope this short explanation gives you a better understanding of what I am trying to do, if not, please let me know.

**Comment by Mark-Falconbridge-i2** [comment]
Ah, I see, can you use the `seedId` property on the seed?

**Comment by Timon-IW** [comment]
The seedId is not the same as the one i gave it, it's the Id that is given the entity when copying it into the chart.

**Comment by Mark-Falconbridge-i2** [comment]
Can you post a minimal example of what you're trying to do because I'm not sure I fully understand what you're doing with the `connectorKeys` in your first post.

P.S. Has your connector indicated that it returns persistentIds? I think you'd at least need to do that if you ever want to be able to do something with the same id again. https://i2group.github.io/analyze-connect-node-sdk/api/i2connect.services.icoreserviceconfig.haspersistentresultids.html.

**Comment by Timon-IW** [comment]
Sure, i will try. 
So on the first service I create an entity, like this: 
```
 const personEntity = result.addEntity(Person, data.P_ID);
 personEntity.setProperty('Rolle', data.Rolle); 
 personEntity.setProperty('Name', data.Name);
 ...
```
The data object is a JSON from a MySQL database, the P_ID is a unique identifier that should only be known by the database, it should not be a property on the Entity itself.
Then, when I am copying it into a chart, it got its own ID which is the seedId:
![grafik](https://github.com/user-attachments/assets/305f8cff-d916-407f-9c6b-32b9c6bda101)

I then select it for a seeded search and on this seeed service I try to get the P_ID from the seeded Entity to send another SQL to find the right dataset in the database.
I was certain that i got the id from the connectorKeys because in another "older" (like 3-4 month old) connector  i used it like this: 
```
seeds.entities.forEach((seed) => {
        if (seed.isType(Person)) {
          personSeedIds.push(seed.connectorKeys[0].id);
        }
});
```

**Comment by Mark-Falconbridge-i2** [comment]
I think you need to use a sourceIdentifier as an id rather than a plain string if you want to do something like that.

The api is documented here https://i2group.github.io/analyze-connect-node-sdk/api/i2connect.services.iresult.addentity_1.html and there's an example of it being set here https://github.com/i2group/analyze-connect-node-sdk/blob/main/samples/example-connector/src/index.ts#L53 and then consumed later here https://github.com/i2group/analyze-connect-node-sdk/blob/main/samples/example-connector/src/index.ts#L676.

**Comment by Timon-IW** [comment]
Oh, okay.  I thought that those were only to conserve the ID when loading it into the IStore.
Thank you for your help. It now works the way I wanted it to.
