### ISSUE TITLE
Logging when setProperties failed

### ISSUE THREAD

**Issue by stvdo** [i2group/analyze-connect-node-sdk#36]
Good afternoon,

My connector failed when the short description was longer than 2500 characters.

With a try/catch I tried to log which properties gave the error. But the debugger doesn't enter the catch. What can I do to catch the detailed error message?

```
const logger = createLogger();
const maxLengthSD = 2500;

export function addCase(datum: CaseDetailResponse, result: services.IResult): records.IResultEntityRecord<typeof FraudCase> {
  const uniqueId = datum.id;
  const entity = result.addEntity(FraudCase, uniqueId);

  try {
    entity.setProperties({
      'Case Number': datum.pt_casenumber,
      'Short Description': datum.pt_shortdescription.length > maxLengthSD ? datum.pt_shortdescription.slice(0, maxLengthSD) : datum.pt_shortdescription,
      'Other Information': datum.pt_otherinformation != null ? datum.pt_otherinformation : "",
    });
  } catch (error) {
    logger.error(`Error setting properties addCase with ID ${datum.id}:`, error);
  }

  entity.setSourceReference(sourceReference);

  return entity;
};
```

**Comment by Colvin-Cowie-i2** [comment]
Hello, you say your connector failed. Does that mean you're getting an error in the connector itself, or is the query failing?
I would expect that the failure is in the gateway server, as it will validate the data returned from the connector against the schema.
The default maximum length of a SINGLE_LINE_STRING property is `250` characters, though this can be increased in the schema using Schema Designer.

**Comment by stvdo** [comment]
Hi Colvin,

With failed I mean I got this error in ANB and I can't find logs which say that I try to add too much characters to the field 'Short Description'.

I changed the max length already to 2500, but the response has >2500 characters.

![image](https://github.com/user-attachments/assets/c5b237b9-1942-41b2-bbde-d34f6fc8efd3)

**Comment by Colvin-Cowie-i2** [comment]
> I can't find logs which say that I try to add too much characters

The error will be in the server log.

- If you're using a toolkit deployment check the `i2_Analysis_Repository.log`.
- If you're using a containerized deployment then check the docker logs for the liberty container by running `docker logs <container>`, or using Docker Desktop.

**Comment by stvdo** [comment]
Hi Colvin,

I found the logs indeed, thank you.

However, it would be nice to have all the connector related logs on the same place. Is this somehow possible? 

In the server.json I added this config. I expected the details of the error in the logs/i2ConnectorServer.log.
```
 "log": {
    "level": "debug",
    "fileLogging": {
      "enabled": true,
      "dir": "logs"
    }
  }
```

**Comment by Colvin-Cowie-i2** [comment]
I understand. The issue is that the Gateway server initiates the request to the connector, so it's validating the connector's response, so it isn't possible for it to send the result of validation to the connector.

Getting all the logs into one place is something you would need to arrange externally, e.g. using something like Logstash

**Comment by stvdo** [comment]
I understand. Is the validation done with the Gateway schema or with the connector schema?

Would it be possible to add a new validation function in the Gateway which can be called before returning the case entity (in the addCase function)?

**Comment by Colvin-Cowie-i2** [comment]
> Is the validation done with the Gateway schema or with the connector schema?

If the connector has a schema with that entity type then that's what will be used by default for the validation.

>Would it be possible to add a new validation function in the Gateway which can be called before returning the case entity (in the addCase function)?

I'm afraid that doesn't fit with the flow of the interactions between the Gateway and Connector. The interaction is along the lines below, where the calls to addCase are all happening within the Connector itself. It would require a lot of communication between the Gateway and Connector.

```mermaid
sequenceDiagram
    Client->>Gateway: /acquire {query conditions+seeds}
    Gateway->>Connector: /validate {query conditions+seeds}
    Connector-->>Gateway: {validation response}
    Gateway->>Connector: /query {query conditions+seeds}
    Connector->>Connector: addCase[s]
    Connector-->>Gateway: {query response}
    Gateway->>Gateway: Process and store results
    Gateway-->>Client: Results
```

Though I guess what you're really asking is whether the Connector SDK could provide some of the validation that the Gateway provides for more immediate feedback and unit testing? Though such validation would only be a subset of what the Gateway does, because the Connector wouldn't have all the context of the system.
Alternatively, we could look at providing a configuration option that tells the Gateway to truncate the data rather than rejecting it.

I suggest you raise an RFE if you want to take this further.

**Comment by stvdo** [comment]
Thanks a lot Colvin for the clear overview!

I'll raise an RFE to add a validation function (subset of the Gateway one) in the Connector SDK.
